# archibald.toml

environment = "Development"


[log]
level = "debug"  # Supports: debug, info, warn, error
file_name = "archibald_server.log"  # 

[server]
address = "127.0.0.1"
port = 8080

[web]
static_root = "./static_content"