[package]
name = "archibald"
version = "0.1.0"
edition = "2021"
envy = "0.4"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
directories = "4.0.1"
log = "0.4"

serde = {version = "1.0.144", features = ["derive"] }
toml = "0.5.10"
