/*
* Archibald: a loyal web server
* Main config module
* Author: @danielcuthbert
* This is the main configuration module for Archibald. 
* It allows you to set a wide range of things he has to 
* serve and listen to. 
*/

// Main Server Portion

[server]
address = "127.0.0.1"
port = "8080"

[log]
level = debug

[content]
static_path = "/static_content"
default_path = ""